version: 0.2
phases:
  pre-build:
    commands:
      -echo "Pre-build Phase"
    build:
      commands:
        -echo "Build Phase"
        -mvn clean prepare-package war:explode
      post-build:
        commands:
          -echo "Post Build"
          -mv target/deploy ./
    artifacts:
      files:
        -deploy/**/*
